import type { Stream, FlashSale, ChatMessage } from "./types";

const now = Date.now();
const FLASH_END = new Date(now + 8 * 60 * 1000 + 34 * 1000).toISOString();
const FLASH_START = new Date(now - 5 * 60 * 1000).toISOString();
const SCHED_1 = new Date(now + 2 * 60 * 60 * 1000).toISOString();
const SCHED_2 = new Date(now + 5 * 60 * 60 * 1000).toISOString();
const SCHED_3 = new Date(now + 24 * 60 * 60 * 1000).toISOString();

export const MOCK_STREAMS: Stream[] = [
  {
    id: 1,
    hostId: 10,
    hostName: "Sarah Beauty Official",
    title: "Flash Sale Skincare Korea 90% OFF — Habis Sekarang!",
    status: "live",
    startedAt: new Date(now - 30 * 60 * 1000).toISOString(),
    endedAt: null,
    viewerPeak: 1842,
    viewerCount: 1842,
    gradient: "linear-gradient(135deg,#F472B6,#8B5CF6)",
    icon: "✨",
    category: "Kecantikan",
  },
  {
    id: 2,
    hostId: 11,
    hostName: "KickZone Official",
    title: "Sneakers Limited Nike Air Zoom — Pre-Order Buka!",
    status: "live",
    startedAt: new Date(now - 45 * 60 * 1000).toISOString(),
    endedAt: null,
    viewerPeak: 3201,
    viewerCount: 3201,
    gradient: "linear-gradient(135deg,#6366F1,#EC4899)",
    icon: "👟",
    category: "Fashion",
  },
  {
    id: 3,
    hostId: 12,
    hostName: "GadgetMania ID",
    title: "Laptop & Aksesoris Murah Parah — Flash 1 Jam!",
    status: "live",
    startedAt: new Date(now - 20 * 60 * 1000).toISOString(),
    endedAt: null,
    viewerPeak: 987,
    viewerCount: 987,
    gradient: "linear-gradient(135deg,#3B82F6,#06B6D4)",
    icon: "💻",
    category: "Elektronik",
  },
  {
    id: 4,
    hostId: 13,
    hostName: "Batik Nusantara",
    title: "Fashion Show Batik Modern 2026 — Koleksi Terbaru",
    status: "scheduled",
    startedAt: null,
    endedAt: null,
    viewerPeak: 0,
    viewerCount: 0,
    gradient: "linear-gradient(135deg,#F59E0B,#EF4444)",
    icon: "👗",
    category: "Fashion",
    scheduledAt: SCHED_1,
  },
  {
    id: 5,
    hostId: 14,
    hostName: "Chef Yuda Kitchen",
    title: "Bumbu Rahasia & Peralatan Masak Profesional",
    status: "scheduled",
    startedAt: null,
    endedAt: null,
    viewerPeak: 0,
    viewerCount: 0,
    gradient: "linear-gradient(135deg,#F97316,#FCD34D)",
    icon: "🍳",
    category: "Kuliner",
    scheduledAt: SCHED_2,
  },
  {
    id: 6,
    hostId: 15,
    hostName: "RTX Gaming Store",
    title: "GPU RTX 5090 Flash Sale 40% OFF — Stok 50 Unit!",
    status: "scheduled",
    startedAt: null,
    endedAt: null,
    viewerPeak: 0,
    viewerCount: 0,
    gradient: "linear-gradient(135deg,#10B981,#3B82F6)",
    icon: "🎮",
    category: "Elektronik",
    scheduledAt: SCHED_3,
  },
  {
    id: 7,
    hostId: 10,
    hostName: "Sarah Beauty Official",
    title: "Skincare Lokal Haul: Review & Giveaway",
    status: "ended",
    startedAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
    endedAt: new Date(now - 1 * 60 * 60 * 1000).toISOString(),
    viewerPeak: 2100,
    viewerCount: 0,
    gradient: "linear-gradient(135deg,#94A3B8,#64748B)",
    icon: "💄",
    category: "Kecantikan",
  },
  {
    id: 8,
    hostId: 16,
    hostName: "LuxeCloset",
    title: "Jam Tangan Premium Pre-Loved — Autentik 100%",
    status: "ended",
    startedAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
    endedAt: new Date(now - 3.5 * 60 * 60 * 1000).toISOString(),
    viewerPeak: 1500,
    viewerCount: 0,
    gradient: "linear-gradient(135deg,#9CA3AF,#6B7280)",
    icon: "⌚",
    category: "Aksesoris",
  },
];

export const MOCK_FLASH_SALES: Record<number, FlashSale> = {
  1: {
    id: 1,
    productId: 1,
    productName: "Serum Vitamin C + Collagen Gold Brightening 30ml",
    productDescription:
      "Formula eksklusif dari Korea dengan konsentrasi Vitamin C 20% dan Collagen Marine yang mencerahkan kulit dalam 7 hari. Cocok untuk semua jenis kulit, BPOM terdaftar.",
    streamId: 1,
    salePrice: 89_000,
    saleStock: 47,
    totalStock: 200,
    quotaPerUser: 2,
    startTime: FLASH_START,
    endTime: FLASH_END,
    status: "active",
    normalPrice: 299_000,
  },
  2: {
    id: 2,
    productId: 2,
    productName: "Nike Air Zoom Pegasus 42 — Midnight Colorway",
    productDescription:
      "Collab eksklusif Nike × Sacai edisi terbatas. Upper mesh breathable, midsole Air Zoom generasi terbaru. Hanya 200 pasang worldwide.",
    streamId: 2,
    salePrice: 1_250_000,
    saleStock: 23,
    totalStock: 50,
    quotaPerUser: 1,
    startTime: FLASH_START,
    endTime: new Date(now + 15 * 60 * 1000).toISOString(),
    status: "active",
    normalPrice: 2_400_000,
  },
  3: {
    id: 3,
    productId: 3,
    productName: 'Laptop Gaming ASUS ROG Zephyrus G16 — RTX 4070',
    productDescription:
      "Intel Core i9-14900H, RTX 4070 165W, 32GB DDR5, 1TB NVMe SSD. Garansi resmi ASUS 2 tahun.",
    streamId: 3,
    salePrice: 18_500_000,
    saleStock: 8,
    totalStock: 20,
    quotaPerUser: 1,
    startTime: FLASH_START,
    endTime: new Date(now + 3 * 60 * 1000).toISOString(),
    status: "active",
    normalPrice: 24_999_000,
  },
};

const CHAT_POOL: Omit<ChatMessage, "id">[] = [
  { userId: 101, userName: "Dewi R.", content: "Wah murah banget kak! ✨" },
  { userId: 102, userName: "Budi S.", content: "Ada varian warna lain gak?" },
  { userId: 103, userName: "Sari K.", content: "BELI BELI BELI 🛒🛒🛒" },
  { userId: 104, userName: "Andi W.", content: "Kak ini original kan? Ada sertifikatnya?" },
  { userId: 105, userName: "Nisa F.", content: "Sudah coba kak? Hasilnya gimana?" },
  { userId: 106, userName: "Reza P.", content: "Stok tinggal dikit banget! Gaskeun" },
  { userId: 107, userName: "Tika M.", content: "Udah order 2 sekaligus hehe 😄" },
  { userId: 108, userName: "Hendra G.", content: "Ongkir gratis kan kak?" },
  { userId: 101, userName: "Dewi R.", content: "Buat hadiah ulang tahun perfect banget 🎁" },
  { userId: 109, userName: "Yuli A.", content: "Countdown tinggal bentar lagi woy!!" },
  { userId: 110, userName: "Fajar D.", content: "Kak demo-in dulu dong" },
  { userId: 103, userName: "Sari K.", content: "Udah 3x beli produk ini, ga pernah kecewa!" },
  { userId: 111, userName: "Maya S.", content: "Harga segini super worth it 🙌" },
  { userId: 112, userName: "Doni T.", content: "Kapan restock kak? Terlambat nih" },
  { userId: 105, userName: "Nisa F.", content: "Testimoni nyata: kulit jadi glowing dalam seminggu" },
  { userId: 113, userName: "Putri L.", content: "❤️❤️❤️" },
  { userId: 102, userName: "Budi S.", content: "Paket bundling ada gak?" },
  { userId: 114, userName: "Agus R.", content: "Mantap kak terimakasih 🙏" },
  { userId: 115, userName: "Lina H.", content: "Set alarm buat flash sale berikutnya!" },
  { userId: 116, userName: "Bayu K.", content: "Yang masih ragu: BELI AJA, gak nyesel!" },
];

export function getChatPool(): Omit<ChatMessage, "id">[] {
  return CHAT_POOL;
}
